Class CHUBXL.MSG.SibelmedDiaH Extends CHUBXL.MSG.SibelmedFtransHeader [ ClassType = persistent, Not ProcedureBlock ]
{

Property COM As %String;

Property CP As %String;

Property DEST As %String;

Property DNAIS As %String;

Property ETCIV As %String;

Property FILLER As %String;

Property LANG As %String;

Property LNAIS As %String;

Property NADM As %String;

Property NAT As %String;

Property NOM As %String;

Property PAYS As %String;

Property PRENOM As %String;

Property RUE As %String;

Property SEXE As %String;

Property TEL As %String;

Property TIMESTAMP As %String;

Storage Default
{
<Data name="SibelmedDiaHDefaultData">
<Subscript>"SibelmedDiaH"</Subscript>
<Value name="1">
<Value>COM</Value>
</Value>
<Value name="2">
<Value>CP</Value>
</Value>
<Value name="3">
<Value>DEST</Value>
</Value>
<Value name="4">
<Value>DNAIS</Value>
</Value>
<Value name="5">
<Value>ETCIV</Value>
</Value>
<Value name="6">
<Value>FILLER</Value>
</Value>
<Value name="7">
<Value>LANG</Value>
</Value>
<Value name="8">
<Value>LNAIS</Value>
</Value>
<Value name="9">
<Value>NADM</Value>
</Value>
<Value name="10">
<Value>NAT</Value>
</Value>
<Value name="11">
<Value>NOM</Value>
</Value>
<Value name="12">
<Value>PAYS</Value>
</Value>
<Value name="13">
<Value>PRENOM</Value>
</Value>
<Value name="14">
<Value>RUE</Value>
</Value>
<Value name="15">
<Value>SEXE</Value>
</Value>
<Value name="16">
<Value>TEL</Value>
</Value>
<Value name="17">
<Value>TIMESTAMP</Value>
</Value>
</Data>
<DefaultData>SibelmedDiaHDefaultData</DefaultData>
<Type>%Library.CacheStorage</Type>
}

}
