/// Languages
/// Created from: http://brDocStampTest:8080/timestamping/services/JournalEntryService?xsd=common-1-0.xsd
Class CHUBXL.WS.HealthConnect.common.LanguageType Extends %String [ ClassType = datatype, CompileAfter = , ProcedureBlock ]
{

Parameter ELEMENTQUALIFIED = 1;

Parameter MAXLEN;

Parameter NAMESPACE = "urn:be:healthconnect:timestamping:ws:1_0:common";

Parameter VALUELIST = ",NL,FR,EN";

}
