Class CHUBXL.WS.Cosite.Response.GetUserLinkResponse Extends Ens.Request [ ProcedureBlock ]
{

Property GetUserLinkResult As CHUBXL.WS.Cosite.common.GetUserLinkResponse;

Storage Default
{
<Data name="GetUserLinkResponseDefaultData">
<Subscript>"GetUserLinkResponse"</Subscript>
<Value name="1">
<Value>GetUserLinkResult</Value>
</Value>
</Data>
<DefaultData>GetUserLinkResponseDefaultData</DefaultData>
<Type>%Library.CacheStorage</Type>
}

}
