Class CHUBXL.WS.Response.AddAttachedJournalEntryResponse Extends Ens.Response [ ClassType = persistent, ProcedureBlock ]
{

Property ResponseInfo As CHUBXL.WS.HealthConnect.common.ResponseInfoType;

Storage Default
{
<Data name="AddAttachedJournalEntryResponseDefaultData">
<Subscript>"AddAttachedJournalEntryResponse"</Subscript>
<Value name="1">
<Value>ResponseInfo</Value>
</Value>
</Data>
<DefaultData>AddAttachedJournalEntryResponseDefaultData</DefaultData>
<Type>%Library.CacheStorage</Type>
}

}
