Class CHUBXL.WS.Response.AddJournalEntryResponse Extends Ens.Response [ ClassType = persistent, ProcedureBlock ]
{

Property ResponseInfo As CHUBXL.WS.HealthConnect.common.ResponseInfoType;

Storage Default
{
<Data name="AddJournalEntryResponseDefaultData">
<Subscript>"AddJournalEntryResponse"</Subscript>
<Value name="1">
<Value>ResponseInfo</Value>
</Value>
</Data>
<DefaultData>AddJournalEntryResponseDefaultData</DefaultData>
<Type>%Library.CacheStorage</Type>
}

}
